# Givens Rotations

Step-by-step example of incremental QR factorization as outlined in *iSAM: Incremental Smoothing and Mapping* by Kaess et al.

In [1]:
import numpy as np

Create a random matrix $\mathbf{A}$ to factorize

In [2]:
#A = np.random.rand(4,4)
#A = np.matrix([[1,2,3,4],[5,-6,-7,8],[-9,-10,-1,11],[12,-13,-14,-15]])
A = np.matrix([[1,2,3], [4,-5,-6], [-7, 8, 9]])
print(A)

[[ 1  2  3]
 [ 4 -5 -6]
 [-7  8  9]]


In [3]:
def givensStep(A):
    '''
    performs a single givens rotation, and outputs result
    '''
    # Initialize givens rotation matrix
    G = np.eye(len(A))
    getout = False
    for k in range(len(A)):
        for i in range(k+1, len(A)):
            print(A[i,k])
            if np.abs(A[i,k]) >= 1e-10:
                alpha = A[k,k]
                beta = A[i,k]
                print("alpha = " + str(alpha) + ", beta = " + str(beta))
                # Compute Givens Rotation Matrix according to criteria:
                if np.abs(beta) > np.abs(alpha):
                    c = -alpha/( beta*np.sqrt(1 + (alpha/beta)**2) )
                    s = 1/( np.sqrt(1 + (alpha/beta)**2) )
                else:
                    c = 1/( np.sqrt(1 + (beta/alpha)**2) )
                    s = -beta/( alpha*np.sqrt(1 + (beta/alpha)**2) )
                G[k,k] = c
                G[i,k] = -s
                G[k,i] = s
                G[i,i] = c
                print("Givens Rotation")
                print(G)
                return(G)
                getout = True
                break
        if getout:
            break
            
        
        
            

In [4]:
G = givensStep(A)

4
alpha = 1, beta = 4
Givens Rotation
[[-0.24253563  0.9701425   0.        ]
 [-0.9701425  -0.24253563  0.        ]
 [ 0.          0.          1.        ]]


In [5]:
G.transpose()*A

matrix([[-4.12310563,  4.36564125,  5.09324813],
        [ 0.        ,  3.15296313,  4.36564125],
        [-7.        ,  8.        ,  9.        ]])

In [6]:
A

matrix([[ 1,  2,  3],
        [ 4, -5, -6],
        [-7,  8,  9]])

In [7]:
G2 = givensStep(G.transpose()*A)

0.0
-7.0
alpha = -4.123105625617661, beta = -7.0
Givens Rotation
[[-0.50751922  0.          0.86164044]
 [ 0.          1.          0.        ]
 [-0.86164044  0.         -0.50751922]]


In [8]:
G2*G*A

matrix([[ 0.12309149,  0.24618298,  0.36927447],
        [-0.9701425 ,  1.21267813,  1.45521375],
        [ 3.55263453, -4.06015375, -4.56767297]])

In [9]:
alpha = 7.071067811865475
beta = 4.0


In [10]:
1/np.sqrt(1+(beta/alpha)**2)

0.8703882797784892

In [11]:
-beta/(alpha*np.sqrt(1+(beta/alpha)**2))

-0.492365963917331

In [12]:
A = np.matrix([[6,5,0], [5,1,4], [0,4,3]])

In [18]:
A

matrix([[6, 5, 0],
        [5, 1, 4],
        [0, 4, 3]])

In [15]:
G = np.matrix([[0.7682, 0.6402, 0], [-0.6402, 0.7682, 0], [0, 0, 1]])

In [19]:
G*A

matrix([[ 7.8102e+00,  4.4812e+00,  2.5608e+00],
        [-2.0000e-04, -2.4328e+00,  3.0728e+00],
        [ 0.0000e+00,  4.0000e+00,  3.0000e+00]])