# Givens Rotations

Step-by-step example of incremental QR factorization as outlined in *iSAM: Incremental Smoothing and Mapping* by Kaess et al.

In [2]:
import numpy as np

Create a random matrix $\mathbf{A}$ to factorize

In [3]:
#A = np.random.rand(4,4)
A = np.matrix([[1,2,3,4],[5,-6,-7,8],[-9,-10,0,11],[12,-13,-14,-15]])
print(A)

[[  1   2   3   4]
 [  5  -6  -7   8]
 [ -9 -10   0  11]
 [ 12 -13 -14 -15]]


In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
def givensStep(A):
    '''
    performs a single givens rotation, and outputs result
    '''
    # Initialize givens rotation matrix
    G = np.eye(4)
    getout = False
    for k in range(len(A)):
        for i in range(k+1, len(A)):
            if A[i,k] != 0:
                alpha = A[k,k]
                beta = A[i,k]
                print("alpha = " + str(alpha) + ", beta = " + str(beta))
                # Compute Givens Rotation Matrix according to criteria:
                if beta == 0:
                    c = 1
                    s = 0
                elif np.abs(beta) > np.abs(alpha):
                    c = -alpha/( beta*np.sqrt(1 + (alpha/beta)**2) )
                    s = 1/( np.sqrt(1 + (alpha/beta)**2) )
                else:
                    c = 1/( np.sqrt(1 + (beta/alpha)**2) )
                    s = -beta/( alpha*np.sqrt(1 + (beta/alpha)**2) )
                G[k,k] = c
                G[i,k] = -s
                G[k,i] = s
                G[i,i] = c
                print("Givens Rotation")
                print(G)
                return(G)
                getout = True
                break
        if getout:
            break
            
        
        
            

In [19]:
G = givensStep(A)

alpha = 1, beta = 5
Givens Rotation
[[-0.19611614  0.98058068  0.          0.        ]
 [-0.98058068 -0.19611614  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [22]:
G*A

matrix([[  4.70678724,  -6.27571632,  -7.45241314,   7.06018086],
        [ -1.96116135,  -0.78446454,  -1.56892908,  -5.49125178],
        [ -9.        , -10.        ,   0.        ,  11.        ],
        [ 12.        , -13.        , -14.        , -15.        ]])

In [27]:
G.transpose()*A

matrix([[-5.09901951e+00,  5.49125178e+00,  6.27571632e+00,
         -8.62910995e+00],
        [ 2.77555756e-17,  3.13785816e+00,  4.31455497e+00,
          2.35339362e+00],
        [-9.00000000e+00, -1.00000000e+01,  0.00000000e+00,
          1.10000000e+01],
        [ 1.20000000e+01, -1.30000000e+01, -1.40000000e+01,
         -1.50000000e+01]])

In [28]:
np.set_printoptions(suppress=True)


In [34]:
G2 = givensStep(G.transpose()*A)

alpha = -5.0990195135927845, beta = 2.7755575615628914e-17
Givens Rotation
[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [37]:
G2.transpose()*G.transpose()*A

matrix([[ -0.19611614,  -0.39223227,  -0.58834841,  -0.78446454],
        [ -0.98058068,   1.17669681,   1.37281295,  -1.56892908],
        [ -9.        , -10.        ,   0.        ,  11.        ],
        [ 12.        , -13.        , -14.        , -15.        ]])